version: '#{build}'

image:
- Ubuntu
- Visual Studio 2015

build_script:

- cmd: appveyor\build.bat
- sh: chmod +x appveyor/build.sh && ./appveyor/build.sh

artifacts:
- path: ESMB-win64*
- path: ESMB-amd64*